kind: Service
apiVersion: v1
metadata:
  name: holidays-crud
  labels:
    app: holidays-crud
spec:
  type: ClusterIP
  selector:
    app: holidays-crud
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: holidays-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holidays-crud
  template:
    metadata:
      labels:
        app: holidays-crud
        version: v1
    spec:
      containers:
      - name: holidays-crud
        image: holidays-crud
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
